### ISSUE TITLE
Can not test container build

### ISSUE THREAD

**Issue by jonas-schulze** [EuroTUG/trilinos-docker#14]
The README advises to test the container build as follows.

```bash
cd /opt/trilinos/build
ctest -j <numProc>
```

The directory `/opt/trilinos/build` [does not exist](https://github.com/EuroTUG/trilinos-docker/blob/bfed0fcdd0ff75ab2823cb3d7e5714d208ebe418/dockerfiles/trilinos_demo#L47C17-L47C17).

**Comment by mayrmt** [comment]
@jonas-schulze, thanks for bringing this to our attention.

We removed the `build/` directory just recently, since it is not required for the tutorial. We just forgot to update the instructions in the `README`. PR #15 took care of this.

Sorry for the inconvenience!
